apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tss-hall
  namespace: tss-hall
spec:
  generators:
    - git:
        repoURL: https://github.com/Thxzzzzz/gitops-demo-apps.git
        revision: HEAD
        # pathParamPrefix: example
        directories:
          - path : "tss/hall/*"
          - path: "*/base"
            exclude: true
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: gitops-demo-github
      source:
        repoURL: https://github.com/Thxzzzzz/gitops-demo-apps.git
        targetRevision: HEAD
        path:  '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: tss-hall