apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tss-hall
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/Thxzzzzz/gitops-demo-apps.git
      revision: HEAD
      directories:
      - path: tss/hall/*
      - path: tss/hall/base
        exclude: true
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Thxzzzzz/gitops-demo-apps.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace:  gitops-demo
      syncPolicy:
        automated: {}

        