apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base/deployment

labels:
- pairs:
    app: demobiz2-kustomize

images:
- name: app_image
  newName: 379809513/demo-biz
  newTag: v2.2

patches:
- path: app_patch.yaml
  target:
    kind: Deployment